---

- name: Playbook to unconfigure interfaces and remove OSPF
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
  tasks:
  - name: Remove OSPF route from interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interface_ospf:
      interface: "{{ item.nxos_ospf_interface }}"
      ospf: "{{ item.nxos_ospf_number }}"
      area: "{{ item.nxos_ospf_area }}"
      state: absent
  - name: Unconfigure interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ item.nxos_ospf_interface }}"
      state: deleted
  - name: Remove interface IPv4 address
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_l3_interface:
      name: "{{ item.nxos_ospf_interface }}"
      ipv4: "{{ item.nxos_loopback0_ip }}"
      state: present

- name: Playbook to Configure interfaces for OSPF
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
  tasks:
  - name: Create interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ item.nxos_ospf_interface }}"
        description: "{{ item.nxos_ospf_interface }} Configured by Ansible"
        enabled: true
      state: merged

  - name: Set interface IPv4 address
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_l3_interface:
      name: "{{ item.nxos_ospf_interface }}"
      ipv4: "{{ item.nxos_loopback0_ip }}"
      state: present

  - name: Add OSPF route to interface
    loop: "{{ configure_ospf }}"
    cisco.nxos.nxos_interface_ospf:
      interface: "{{ item.nxos_ospf_interface }}"
      ospf: "{{ item.nxos_ospf_number }}"
      area: "{{ item.nxos_ospf_area }}"
      state: present