default:
    image: priel/devnet-nxos-bootcamp-runner:0.1.0
test:
    script:
    - cd pyats && pyats run job job.py --testbed-file devnet_sandbox.yaml --trigger-datafile pre_trigger_datafile.yaml --html-logs pre_snapshots
    - cd .. && python nxos-automation.py
    - cd pyats && pyats run job job.py --testbed-file devnet_sandbox.yaml --trigger-datafile post_trigger_datafile.yaml --html-logs post_snapshots
    artifacts:
        paths:
        - pyats/pre_snapshots/TaskLog.job.html
        - pyats/post_snapshots/TaskLog.job.html
        when: always
        #test
