---

- name: Playbook to unconfigure VLAN interfaces for OSPF and HSRP
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli

  tasks:
  - name: Delete VLAN
    cisco.nxos.nxos_vlans:
      config:
      - vlan_id: "{{ vlan_106_id }}"
      state: deleted
    tags: no_vlan

  - name: Delete OSPF route from interface
    cisco.nxos.nxos_interface_ospf:
      interface: "Vlan{{ vlan_106_id }}"
      ospf: "{{ ospf_number }}"
      area: "{{ ospf_area }}"
      state: absent
    tags: no_ospf

  - name: Delete HSRP config
    cisco.nxos.nxos_hsrp:
      group: "{{ hsrp_area }}"
      vip: "{{ hsrp_vip }}"
      interface: "vlan{{ vlan_106_id }}"
      state: absent
    tags: no_hsrp

  - name: Remove interface IPv4 address
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: "vlan{{ vlan_106_id }}"
      state: deleted
    tags: no_ipv4

  - name: run configure commands
    cisco.nxos.nxos_command:
      commands:
      - configure terminal
      - command: no interface Vlan{{ vlan_106_id }}
    tags: no_interface