---

# Run command
# ansible-playbook -i hosts.yaml nxos_list_vlans.yaml --ask-vault-pass --extra-vars "con_var=httpapi"​
# ansible-playbook -i hosts.yaml nxos_list_vlans.yaml --vault-password-file vault_pass.txt --extra-vars "con_var=network_cli"

- name: List NXOS VLANs
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: "{{ con_var }}"

  tasks:
    - name: Gather all legacy facts
      cisco.nxos.nxos_facts:
        gather_subset: legacy
      register: nxos_facts

    - debug:
        var: nxos_facts['ansible_facts']['ansible_net_vlan_list']
