---

- name: Playbook for cisco.nxos.nxos_command
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
  
  tasks:
  - name: run multiple commands on remote nodes
    cisco.nxos.nxos_command:
      commands:
      - show version
      - show interfaces
    register: nxos_version_interfaces

  - debug:
      var: nxos_version_interfaces
