---

- name: Playbook to Enable NX-OS features via network_cli
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: Enable Features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop:
        - interface-vlan
        - bgp
