---

- name: Playbook to unconfigure interfaces for BGP and unconfigure BGP
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli

  tasks:
  - name: Delete interface
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ bgp_interface }}"
      state: deleted
    tags: no_interface

  - name: run configure commands
    cisco.nxos.nxos_command:
      commands:
      - configure terminal
      - command: no interface {{ bgp_interface }}
    tags: no_interface

  - name: Remove interface IPv4 address
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "{{ bgp_interface }}"
      state: deleted
    tags: no_l3_interface

  - name: Unconfigure a simple ASN
    cisco.nxos.nxos_bgp:
      asn: "{{ router_bgp }}"
      state: absent
    tags: no_bgp
