---

- name: Playbook to Configure interfaces for OSPF
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli

  tasks:
  - name: Create interface
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ ospf_interface }}"
        description: "{{ ospf_interface }} Configured by Ansible"
        enabled: true
      state: merged

  - name: Set interface IPv4 address
    cisco.nxos.nxos_l3_interface:
      name: "{{ ospf_interface }}"
      ipv4: "{{ loopback0_ip }}"
      state: present

  - name: Add OSPF route to interface
    cisco.nxos.nxos_interface_ospf:
      interface: "{{ ospf_interface }}"
      ospf: "{{ ospf_number }}"
      area: "{{ ospf_area }}"
      state: present
