---

- name: Playbook to Configure interfaces for OSPF
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli

  tasks:
  - name: Create interface
    cisco.nxos.nxos_interfaces:
      config:
      - name: "{{ ospf_interface }}"
        description: "{{ ospf_interface }} Configured by Ansible"
        enabled: true
      state: merged

  # The enabled: true in the task about should add "no shutdown" to the config
  # however it is not. This config command was added to ensure "no shutdown" on
  # the interface.
  - name: run configure commands
    cisco.nxos.nxos_command:
      commands:
      - configure terminal
      - command: interface {{ ospf_interface }}
      - command: no shutdown

  - name: Set interface IPv4 address
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "{{ ospf_interface }}"
          ipv4:
            - address: "{{ loopback0_ip }}"
      state: merged

  - name: Add OSPF route to interface
    cisco.nxos.nxos_interface_ospf:
      interface: "{{ ospf_interface }}"
      ospf: "{{ ospf_number }}"
      area: "{{ ospf_area }}"
      state: present
