---
version: '1.2'
action: configure_bgp
ip: 10.10.20.178
items:
    - loopback0_ip: 192.168.0.2/32
      loopback1_ip: 192.168.2.2/32
      router_bgp: '65532'
      bgp_router_id: 2.2.2.2
      bgp_neighbor: 192.168.0.1
      bgp_remote_as: '6'
      bgp_interface: loopback 1
      bgp_update_source: loopback0