---
loopback0_ip: 192.168.0.1/32
loopback1_ip: 192.168.1.1/32
router_bgp: '65531'
bgp_interface: loopback 1
bgp_router_id: 1.1.1.1
bgp_neighbor: 192.168.0.2
bgp_remote_as: '65532'
bgp_update_source: loopback0